openapi: 3.0.3
info:
  title: Espaço Buddy List Service
  version: 1.0.0
  description: |
    Serviço responsável por listar dados de qualquer tabela no banco, incluindo dados relacionados por chave estrangeira.
    Utiliza consulta dinâmica e introspecção de metadados do PostgreSQL.

servers:
  - url: http://localhost:5003
    description: Serviço List

  - url: http://localhost:5000
    description: Serviço Register

  - url: http://localhost:5004
    description: Serviço Delete
  # - url: https://api.espacobuddy.com/delete
  #   description: Produção

paths:
  /api/list:
    get:
      summary: Listar dados de uma tabela
      tags:
        - Listagem
      description: |
        Lista dados de uma tabela informada com suporte a filtros e recuperação automática de dados relacionados via chaves estrangeiras.
      parameters:
        - in: query
          name: table_name
          required: true
          schema:
            type: string
          description: Nome da tabela a ser consultada.
        - in: query
          name: filters
          style: deepObject
          explode: true
          schema:
            type: object
            additionalProperties:
              type: string
          description: Parâmetros de filtro com base nas colunas da tabela. Qualquer outro parâmetro além de `table_name` será considerado filtro.
      responses:
        '200':
          description: Dados retornados com sucesso.
          content:
            application/json:
              schema:
                type: object
                properties:
                  table:
                    type: string
                    example: rotines
                  data:
                    type: array
                    items:
                      type: object
                      additionalProperties: true
                  foreign_values:
                    type: object
                    additionalProperties:
                      type: object
                      properties:
                        foreign_table_name:
                          type: string
                          example: feeders
                        columns:
                          type: array
                          items:
                            type: string
                        values:
                          type: array
                          items:
                            type: array
                            items:
                              type: string
        '400':
          description: Parâmetro obrigatório ausente ou inválido.
        '404':
          description: Nenhum dado encontrado para a tabela informada.
        '500':
          description: Erro interno no servidor.

  /api/register:
    post:
      summary: Registro dinâmico em qualquer tabela
      tags:
        - Registro
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - table_name
                - fields
              properties:
                table_name:
                  type: string
                  example: feeders
                  description: Nome da tabela no banco de dados.
                fields:
                  type: object
                  additionalProperties:
                    type: string
                  example:
                    name: Alimentador Inteligente
                    status: ativo
                  description: Objeto contendo os campos e valores para inserção.
      responses:
        '201':
          description: Registro criado com sucesso.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Registro inserido com sucesso!
        '400':
          description: Requisição malformada.
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: Nome da tabela e campos são obrigatórios!
        '500':
          description: Erro interno no servidor.
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: Internal Server Error
                  details:
                    type: string
                    example: column "statuss" of relation "feeders" does not exist

  /api/delete:
    delete:
      summary: Deletar dados de uma tabela
      tags:
        - Deleção
      description: |
        Deleta registros de uma tabela especificada com base em filtros dinâmicos.
        Requer ao menos um filtro para evitar deleções em massa.
      parameters:
        - in: query
          name: table_name
          required: true
          schema:
            type: string
          description: Nome da tabela de onde os registros serão deletados.
        - in: query
          name: filters
          style: deepObject
          explode: true
          schema:
            type: object
            additionalProperties:
              type: string
          description: Filtros aplicados à cláusula WHERE. Cada chave será interpretada como uma coluna.
      responses:
        '200':
          description: Registro(s) deletado(s) com sucesso.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Registro(s) deletado(s) com sucesso.
        '400':
          description: Parâmetros obrigatórios ausentes ou cláusula WHERE vazia.
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: Parâmetro "table_name" é obrigatório.
        '404':
          description: Nenhum registro foi deletado com os filtros fornecidos.
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: Nenhum dado foi deletado. Verifique os filtros.
        '500':
          description: Erro interno no servidor.
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: Internal Server Error

components: {}
