# Use a imagem base do Python
FROM python:3.11-slim

# Defina o diretório de trabalho dentro do contêiner
WORKDIR /app

# Copiar o arquivo .env para dentro do contêiner
COPY .env /app/.env

# Copie o arquivo de requisitos para dentro do contêiner
COPY requirements.txt /app/

RUN apt-get update && apt-get install -y git && rm -rf /var/lib/apt/lists/*

# Instale as dependências do projeto
RUN pip install --no-cache-dir -r requirements.txt

# Instale o Gunicorn
RUN pip install gunicorn

# Copie o código da aplicação para dentro do contêiner
COPY . /app/

# Exponha a porta que a aplicação irá rodar
EXPOSE 5000

# Comando para rodar a aplicação com Gunicorn
CMD ["gunicorn", "-b", "0.0.0.0:5000", "register:app"]
